@startuml

entity Hostel {
    Id : Guid
    --
    Students : ICollection<Student>
    ' HostelKeyCodePlaceholder
    --
    Name : string
    ' HostelPropertyCodePlaceholder
}

' EntityCodePlaceholder

' RelationshipCodePlaceholder

@enduml
