@startuml

entity Hostel {
    Id : Guid
    --
    Students : ICollection<Student>
    ' HostelKeyCodePlaceholder
    --
    Name : string
    ' HostelPropertyCodePlaceholder
}

entity Student {
    Id : Guid
    --
    ' StudentKeyCodePlaceholder
    --
    ' StudentPropertyCodePlaceholder
}

' EntityCodePlaceholder

' RelationshipCodePlaceholder

@enduml
